spring:
  application:
    name: book-service
  datasource:
    username: thi
    password: 123
    url: jdbc:postgresql://0.0.0.0:5432/book-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
  flyway:
    url: jdbc:postgresql://0.0.0.0:5432/
    schemas: book-service
    user: thi
    password: 123
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true
server:
  port: 8100